use dunwoody_advising_schema;

INSERT INTO COURSE_TBL
(program_id, term_id, course_code, credits, instruction_type, course_name, course_description)
VALUES
(1, 3, "2200", 3, "Lecture/Lab", "Business Requirements & Analysis", "Software and related technologies must meet the requirements of the stakeholders and the domain for whom the solution is built or configured. Examine scope definition, business, stakeholder and solution requirement definition, select business analysis modeling techniques, the relationship of business requirements and analysis to software design and testing, and a range of methodologies, techniques and approaches."),
(1, 3, "2210", 4, "Lecture/Lab", "Software Design", "Designing software with long-term software quality. Software quality attributes, domain-driven design, software design patterns, and documentation."),
(1, 3, "3110", 3, "Lecture/Lab", "Software Testing", 'Investigate testing methodologies. Tools and techniques in automated testing. Creation of documentation at all stages of testing.'),
(1, 3, "3120", 3, "Lecture", "Software Development Lifecycle", "Explore and implement concepts related to software development pipelines, tooling, and lifecycle. Traditional and emerging software development life cycle models. Techniques for managing software projects. Techniques and tools related to each software development life cycle . Issues include those related to development and maintenance, quality, safety, security assurance, and project management."),
(1, 3, "3240", 3, "Lecture/Lab", "Connected Device Development II", "Advanced study of Internet connected devices. Design and implement applications and services for mobile and smart devices such as smartphones, smart displays, smart speakers. The Android architecture and operating system will be primarily used. Design challenges and opportunities in the mobile/smart device market. Students must have a strong background in application development, the software lifecyle/tooling, and Operating Systems."),
(1, 3, "3310", 4, "Lecture/Lab", "Database Systems", "Accelerated course in data management. Database server technology for enterprise-class data services and complex business logic. Server architecture, data integrity, data types, indexing, constraints, stored procedures, database schemas, normalization, data warehouses, data mining, data cubes. Structured Query Language, database normalization, database management systems (DBMS), implementation-independent database design, and security."),
(1, 3, "3400", 3, "Lecture/Lab", "Operating Systems", "Analyze the purpose of operating systems. Topics include: elements of operating systems, memory and process management, interactions among major components of a computer system, the effects of computer architecture on operating systems, and an examination of how different operating systems (desktop, server, mobile, real-time) impact Software Design."),
(1, 3, "4110", 3, "Lecture/Lab", "Software Engineering Senior Project I", "End-to-end project exhibiting all skills related to the profession. Focus is on requirements elicitation, scheduling, planning, reviews and postmortem, configuration management, and implementation of the project."),
(1, 3, "4111", 2, "Experimental", "Senior Project I", "End-to-end project exhibiting all skills related to the profession. Focus is on requirements elicitation, scheduling, planning, reviews and postmortem, configuration management, and implementation of the project."),
(1, 3, "4210", 3, "Experimental", "Senior Project II", "End-to-end project exhibiting all skills related to the profession. Focus is on requirements elicitation, scheduling, planning, reviews and postmortem, configuration management, and implementation of the project."),
(1, 3, "4310", 3, "Lecture/Lab", "Security I", "Integration of data and users with an emphasis on security will be used in client/server, Internet, intranet/extranet, and other technologies. Review state-of-the-art technologies in each of the basic software and hardware arenas, while emphasizing management models and higher-level analysis using the computer."),
(1, 3, "4400", 3, "Lecture/Lab", "Data Science", "Advanced topics in Data Analysis, Data Science, and Machine Learning. Analyze large datasets. Implement supervised and unsupervised learning.");